spring.application.name=food_delivery

#mongodb configuration
spring.mongodb.uri=mongodb://localhost:27017/food_delivery
spring.mongodb.database=food_delivery

#cloudinary configuration
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

jwt.secret=foodies_super_secret_key_minimum_32_characters
jwt.expiration=3600000

#razorpay configuration
razorpay_key=${RAZORPAY_KEY}
razorpay_secret=${RAZORPAY_SECRET}


#logging.level.org.springframework.security=DEBUG